language: php
php:
    - 7.0
    - 5.6
    - 5.5

before_install:
    - 'sudo apt-get update'
    - 'sudo apt-get install make build-essential automake php5-dev php-pear'
    - 'git clone git://github.com/jedisct1/libsodium.git'
    - 'cd libsodium'
    - 'git checkout 1.0.4'
    - './autogen.sh'
    - './configure && make check'
    - 'sudo make install'
    - 'cd ..'
    - 'pecl install libsodium'
    - 'echo "extension = libsodium.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini'

install:
    - composer --no-interaction --no-progress install
    - composer show --installed

script: vendor/bin/phpunit
